---
- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927 state=present
  sudo: yes
  tags:
    - setup

- name: Add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present
  sudo: yes
  tags:
    - setup

- name: Install mongodb
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-org-tools
  sudo: yes
  notify:
  - restart mongodb
  tags:
    - setup

- name: Install Service
  template: src=mongod.service dest=/etc/systemd/system/mongod.service
  tags:
    - setup

- name: Install Configuration
  template: src=mongod.conf dest=/etc/mongod.conf
  tags:
    - setup

- name: force start mongod
  service: name=mongod state=started enabled=yes
  tags:
    - setup

- pip:
    name: pymongo
  tags:
    - setup
